import type { Metadata } from "next";
import Link from "next/link";
export const metadata:Metadata={title:"About the project"};
export default function AboutPage() {
 return <><section className="about-hero"><span className="eyebrow">ABOUT FORMA</span><h1>A place to start.<br/><em>Room to grow.</em></h1><p>Forma is a course catalog built for Advanced Web Technologies. It brings six areas of modern web development into one place, so you can explore topics and choose what to learn next. This is the starting point of a semester project, with more to come in future labs.</p></section>
 <div className="about-grid"><article><span className="eyebrow">01 / EXPLORE</span><h2>See the bigger picture.</h2><p>Frontend, backend, databases, API design, security and AI: discover how each part contributes to an application.</p></article><article><span className="eyebrow">02 / CHOOSE</span><h2>Find your direction.</h2><p>Search by title, compare credits and separate required courses from electives.</p></article><article><span className="eyebrow">03 / CONNECT</span><h2>Build on what you know.</h2><p>Read suggested topics and prerequisites, then follow related courses to explore the next part of your learning path.</p></article></div>
 <Link href="/courses" className="button primary">Explore the courses ↗</Link>
 <section className="faq"><h2>A few things to know</h2><details><summary>Can I enrol in a course here?</summary><p>This is a student catalog project, not an enrolment service. You can explore course information, but enrolment and lessons are not available here.</p></details><details><summary>Are the topics an official syllabus?</summary><p>The six course records come from Lab 1. The expanded topics, outcomes and prerequisites are illustrative study suggestions added to help you explore each subject.</p></details><details><summary>How do likes work?</summary><p>Each click adds one like during your current page visit. Reloading restores the sample count. Likes are not shared with other users.</p></details><details><summary>Can I share a filtered selection?</summary><p>Yes. Apply your search and filters, then copy the page address. Opening it restores the same search, course type and sorting.</p></details></section></>;
}
